### ISSUE TITLE
FRONTEND: Ecommerce website using Next.js

### ISSUE THREAD

**Issue by theunhackable** [hiteshchoudhary/apihub#85] opened 2024-02-14 06:30 UTC
### Frontend App Title

HMart

### Overview

I would like build an ecommerce application using next.js.
## Frameworks:
- Next.js(TypeScript) - to use the power of different rendering techniques.
- axios - for fetching
- React Query - for state management
- tailwindcss - for styling 
- shadcn - for components
- tabler icons - icons package
 - playwright -  for e2e testing

### Detailed Features

I would like to develop a user friendly e commerce website.
- User can create and login to their accounts.
-  Search and filter functionality for the users.
-  User can browse,  add/remove items from the cart and purchase items based on the selected payment methods.
- Create a CMS page for the ADMIN

### Tech Stack Used

Next.js, React Query

### Built For Platform

The frontend will run on vercel

### Project Path

examples/apps/ecommerce/nextjs-ts-react-query-playwright

**Comment by jwala-anirudh** [comment] 2024-02-14 07:58
Hi @theunhackable 

Thank you for considering FreeApi.app to contribute, we would like to understand more details on your application that will be added in showcase of E-Commerce api.

Please let us know what all modules of E-commerce you are going to cover under this application. We highly encourage if you can cover the [entire suite](https://api.freeapi.app/#/%F0%9F%9B%92%20Ecommerce) of apis that are listed on our docs. Go through them and would be happy to review your development plan before you actually start working. Once we finalise technical document that includes development approach, code architecture, components design, file structure (also covers routing in Next.js) & external dependencies. 

We also take clean code principles into consideration & have iterations during this period, happy to hear more details from you.

Quick note: `playwright`/testing can we avoided for example apps, we are not looking for code coverage under them.

Thank you.

**Comment by theunhackable** [comment] 2024-02-14 10:54
> Hi @theunhackable 
> 
> 
> 
> Thank you for considering FreeApi.app to contribute, we would like to understand more details on your application that will be added in showcase of E-Commerce api.
> 
> 
> 
> Please let us know what all modules of E-commerce you are going to cover under this application. We highly encourage if you can cover the [entire suite](https://api.freeapi.app/#/%F0%9F%9B%92%20Ecommerce) of apis that are listed on our docs. Go through them and would be happy to review your development plan before you actually start working. Once we finalise technical document that includes development approach, code architecture, components design, file structure (also covers routing in Next.js) & external dependencies. 
> 
> 
> 
> We also take clean code principles into consideration & have iterations during this period, happy to hear more details from you.
> 
> 
> 
> Quick note: `playwright`/testing can we avoided for example apps, we are not looking for code coverage under them.
> 
> 
> 
> Thank you.

I have already gone through the spec file. I would love to cover the entire suit. 

I would like to follow the api paths for the routing mostly. 

Component design will be based on shadcn which is a very popular UI and I like its minimalistic look. 

I will be using next.js 14 the latest version.

File structure will follow standard practices like putting different components on their own folders under component folder, hooks, context, providers have their seperate folder.

For linting eslint will be used.
I will also use prettier to format the code

Commit messages will follow conventional commit standards.

**Comment by wajeshubham** [comment] 2024-03-19 05:19
@theunhackable Any tentative timeline for this project just for our reference? Thank you.

**Comment by theunhackable** [comment] 2024-03-21 04:13
> @theunhackable Any tentative timeline for this project just for our reference? Thank you.

It will be completed within a week.

**Comment by jwala-anirudh** [comment] 2024-03-21 07:38
Sounds good @theunhackable, you can open a draft PR (if you are in a state where 50-60% of the implementation is completed) & if you need any feedback we are happy to share

**Comment by jwala-anirudh** [comment] 2024-04-03 05:03
Hi @theunhackable,

Any update on this application? If you are comfortable with the application shape it is in today feel free to open a draft PR so that we are aware of the progress. A similar request by @mirajhad was made, may be you both can work together on this 🙂

**Comment by jwala-anirudh** [comment] 2024-04-05 06:37
Hi @theunhackable,

As we are close to 2 months since the issue is opened & there are no updates from you we are considering this feature addition as invalid & we will be closing this is next 48 hours.

Thank you.

**Closed** 2024-04-07 03:20 UTC
Labels: invalid
