### ISSUE TITLE
The Button is not fully clickable ,a div is blocking it partially 

### ISSUE THREAD

**Issue by itsOmSarraf** [hiteshchoudhary/apihub#14] opened 2023-07-18 15:06 UTC
![image](https://github.com/hiteshchoudhary/apihub/assets/83817663/93a2187b-a51f-4741-83d7-8aeb1cea6c40)

**Comment by itsOmSarraf** [comment] 2023-07-18 15:07
I will fix it.

**Comment by saketverma-03** [comment] 2023-07-18 15:56
![image](https://github.com/hiteshchoudhary/apihub/assets/63857530/efbbceaf-99ca-4931-88c4-f75ff3113dd7)
it is caused by this ` ::before element.`
i can fix this bug assign it to me please

**Comment by jwala-anirudh** [comment] 2023-07-18 16:00
Hi @itsOmSarraf, please raise the bug on the relevant [repo](https://github.com/hiteshchoudhary/freeApiAppWeb) to address the mentioned issue. Since this is related to the FreeApi.app website, the code fix cannot be considered here.

Thanks for sharing!

**Closed** 2023-07-18 16:46 UTC
Labels: invalid
