### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Sarthak-ONS** [hiteshchoudhary/apihub#40] opened 2023-08-05 10:00 UTC
## **Describe the bug**

The bug is in the middlewares/verifyJWT  in auth.middleware.js file 

` req.cookies?.accessToken || req.headers("Authorization")?.split(" ")[1];`

Code breakdown whenever headers are not present, and ends up with Internal Server Error with a status code of 500.

## **To Reproduce**

1. In Postman, Select Authorization Type to No Auth.
2. Then try to access a protected Route
3. Then this error in screenshot below should appear.

## **Expected behavior**

Whenever a "Authorization" header is not present, Server should send Unauthorized request.

## **Solution**

Just change the way of accessing the headers.

` req.cookies?.accessToken || req.headers["Authorization"]?.split(" ")[1];`

## **Screenshots**

![image](https://github.com/hiteshchoudhary/apihub/assets/57105611/1f4fcc2b-fb55-43f0-a627-bc7503e0323f)

## **Desktop (please complete the following information):**

- Client [e.g. postman, thunder client, chrome, safari]

**Comment by wajeshubham** [comment] 2023-08-05 13:00
hey @Sarthak-ONS 

Thank you for raising the issue regarding the bug in the `auth.middleware.js` file. After a thorough review, I couldn't reproduce the problem based on the provided information.

However, there could be some reasons for the discrepancy you encountered. One possibility is that the you might not have installed the required dependencies before running the project, leading to unexpected behavior in case you are running the project without docker. 

To ensure the smooth functioning of the application, please make sure you have executed the following commands to install the dependencies:

```bash
yarn
```

Another possibility is that the project requires Docker to run correctly, and I am assuming that you might not have utilized it while testing.

If you encounter any further issues or need assistance on the same issue, please don't hesitate to ask. Also, I noticed that this issue could be a `good first issue` for someone new to the project, so feel free to contribute and resolve it if you are interested.

Thank you for your contribution to the project, and let us know if there's anything else we can do to help.

Best regards,
FreeAPI team

**Comment by jwala-anirudh** [comment] 2023-08-08 02:54
Hi @Sarthak-ONS,

Can you please check the steps to reproduce? I was not able to reproduce the same as per your sequence of steps v/s screenshot combination.

**Comment by wajeshubham** [comment] 2023-08-11 09:05
Hi @Sarthak-ONS,

Thank you for bringing this to our attention. We've thoroughly reviewed the issue and attempted to reproduce it, but unfortunately, we haven't received any further information or updates from you. As we were unable to replicate the problem ourselves, and without additional details, we will be closing this issue.

If you encounter similar issues in the future or have more information to provide, please don't hesitate to open a new issue. We're here to assist and ensure the best experience for all developers.

Thank you for your understanding 😀.

Best regards,
FreeAPI team

**Comment by Sarthak-ONS** [comment] 2023-08-11 15:56
Hi @jwala-anirudh and @jwala-anirudh, I think the issue still persist on my machine.
I am writing steps again to reproduce the errors-
1. Run Complete Project on Docker and Containers
2. Now, try to access a protected Routes with NO AUTHENTICATION HEADER, as of below image

![image](https://github.com/hiteshchoudhary/apihub/assets/57105611/c48a1701-e8e5-4ee7-b6ad-d0713e452c06)

4. Then the error will be reproduced.

Thanks

**Comment by wajeshubham** [comment] 2023-08-11 17:31
Yes, we have attempted something similar with the protected route, but we are encountering a `401` error, which is the expected behavior. 

I am attaching an image for your reference. If you have any further questions or require assistance, please feel free to ask.

<img width="1056" alt="Screenshot 2023-08-11 at 10 58 29 PM" src="https://github.com/hiteshchoudhary/apihub/assets/62889697/67ef624b-3e42-47be-b1ca-a36cd16cf1d9">

**Comment by Sarthak-ONS** [comment] 2023-08-12 04:03
Please check that cookies are also not being sent by postman.

**Comment by wajeshubham** [comment] 2023-08-12 12:41
Nope! I did clear all the cookies before sending the request. Can you share the screenshot of the error logs/ stack traces from the terminal on what is actually breaking?

**Closed** 2023-08-18 08:06 UTC
Labels: bug, good first issue, needs confirmation
